# Site settings
title: "Knowledge base"
description: > # this means to ignore newlines until "baseurl:"
  Juste another knowledge blog from a freelancer
email: blog@redbeard-consulting.fr
url: 'https://redbeard28.github.io/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'redbeard28'

author:
  name: 'Jérémie CUADRADO'
#  email: jcuadrado@redbeard-consulting.fr
  twitter_username: redbeardjcu
#  facebook_username: 
  github_username:  redbeard28
  linkedin_username:  jeremiecuadrado

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Tipue search settings
tipue_search:
  include:
    pages: true
  exclude:
    files: [search.html]
    
# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
