# Site settings
title: Jekyll-Uno
description: > # this means to ignore newlines until "baseurl:"
  My personal tutorials about containers with docker, cloud infrastructure with AWS azure and openstack. Somes extras about my passions
  like smarthome fibaro, domoticz and arduino, sparkfun, adafruit tutorials.
url: 'https://redbeard28.github.io/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Jérémie CUADRADO'
  email: jcuadrado@redbeard-consulting.fr
  twitter_username: redbeard28
  facebook_username: redbeard28
  github_username:  redbeard28
  linkedin_username:  jeremie_cuadrado

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
