# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:  "Knowledge base from a Geek"
email:  blog@redbeard-consulting.fr
description: > # this means to ignore newlines until "baseurl:"
  My personal tutorials about containers with docker, cloud infrastructure with AWS azure and openstack. Somes extras about my passions
  like smarthome fibaro, domoticz and arduino, sparkfun, adafruit tutorials.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://redbeard28.github.io" # the base hostname & protocol for your site, e.g. http://example.com
timezone: Europe/Paris

# Build settings
#markdown: kramdown
#theme: minima
#gems:
#  - jekyll-feed
###############################################################################
author:
  name: 'Jérémie CUADRADO'
  email: jcuadrado@redbeard-consulting.fr
  twitter_username: redbeard28
  facebook_username: redbeard28
  github_username:  redbeard28
  linkedin_username:  jeremie_cuadrado

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']